Support Lydia rate and transaction typing and description
Clochette-AbsINThe/clochette pull request #118
Opened 2023-03-04 22:03 UTC by xanode

2023-03-04 22:05 UTC, xanode commented
Dis-moi si ça satisfait les besoins du front, comme ça on fusionne dans `dev` puis on fusionne #117 (ça permettera d'éviter le problème de récursivité de #116 a priori).

2023-03-04 22:11 UTC, SamuelGuillemet requested changes

2023-03-04 22:11 UTC, SamuelGuillemet commented on backend/app/schemas/treasury.py
> +    total_amount: float = Field(exclude=True)
Il ne faut pas la possibilité d'update directement les champs de montant (car sinon tu peux modifier la tréso sans laisser de traces)

2023-03-04 22:12 UTC, xanode commented on backend/app/schemas/treasury.py
> +    total_amount: float = Field(exclude=True)
C'est le cas, d'où l'utilisation de `exclude=True`.

2023-03-04 22:40 UTC, SamuelGuillemet commented
Problème sur les transactions de trésorerie, le back essaye quand même d'aller chercher les items dans le crud de la transaction.

### Erreur Python :
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/code/app/core/middleware.py", line 70, in dispatch
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/code/app/db/session.py", line 23, in __call__
    yield session
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/api/v1/endpoints/transaction.py", line 21, in create_transaction
    return await transactions.create(db, obj_in=transaction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/crud/crud_transaction.py", line 38, in create
    for i in range(len(items)):
                   ^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/core/middleware.py", line 73, in dispatch
    body = await self.get_body(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/core/middleware.py", line 56, in get_body
    body = await request.body()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 236, in body
    async for chunk in self.stream():
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 230, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect
``` 

### Détail de la requête envoyée :
```
{
  "amount": 2500,
  "paymentMethod": "CB",
  "description": "Modification du solde",
  "datetime": "2023-03-04T22:39:22.104Z",
  "sale": true,
  "type": "tresorery"
}
```
Envoi sur l'endpoint **POST** `/transaction/`

2023-03-04 22:42 UTC, SamuelGuillemet commented on backend/app/schemas/treasury.py
> +    total_amount: float = Field(exclude=True)
My bad je n'avais pas vu mais ducoup pourquoi tu le met quand même ?

2023-03-04 22:49 UTC, SamuelGuillemet commented
Problème sur les transactions de vente.

### Erreur Python
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/code/app/core/middleware.py", line 70, in dispatch
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/code/app/db/session.py", line 23, in __call__
    yield session
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/api/v1/endpoints/transaction.py", line 21, in create_transaction
    return await transactions.create(db, obj_in=transaction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/crud/crud_transaction.py", line 38, in create
    for i in range(len(items)):
                   ^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/core/middleware.py", line 73, in dispatch
    body = await self.get_body(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/app/core/middleware.py", line 56, in get_body
    body = await request.body()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 236, in body
    async for chunk in self.stream():
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 230, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect
```

### Détail de la requête envoyée 
```
{
  "datetime": "2023-03-04T22:46:07.741Z",
  "sale": true,
  "paymentMethod": "Lydia",
  "amount": 1,
  "items": [
    {
      "table": "out_of_stock",
      "quantity": 1,
      "item": {
        "name": "EcoCup",
        "icon": "Glass",
        "sellPrice": 1,
        "fkId": 2
      }
    }
  ],
  "type": "transaction",
  "description": ""
}
```

Envoi sur l'endpoint **POST** `/transaction`

2023-03-04 23:00 UTC, xanode commented on backend/app/schemas/treasury.py
> +    total_amount: float = Field(exclude=True)
Pour qu'il soit exclu, comme `TreasuryUpdate` hérite de `TreasuryBase`, si je précise pas qu'il faut exclure le champ alors il a les même propriété que dans le parent, i.e. obligatoire.

2023-03-04 23:12 UTC, SamuelGuillemet commented
When trying to update tresory got this 422 error :

```
{
  "detail": [
    {
      "loc": [
        "body",
        "totalAmount"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "cashAmount"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

2023-03-04 23:16 UTC, SamuelGuillemet commented on backend/app/schemas/treasury.py
> +    total_amount: float | None = Field(exclude=True)
Tu devrais plutôt virer ces champs là de base et les mettre que dans le Create mdrr

2023-03-04 23:17 UTC, xanode commented on backend/app/schemas/treasury.py
> +    total_amount: float | None = Field(exclude=True)
Si je les vire ils deviennent obligatoire et non exclus, et ils sont déjà dans `TreasuryCreate` de part l'héritage.

2023-03-05 14:02 UTC, SamuelGuillemet approved these changes

2023-03-05 14:05 UTC, merged